on:
  pull_request:
  push:
    branches:
      - main

name: Integration Test

jobs:
  integration:
    name: test against toast.dev
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            target: toast
          - os: macos-latest
            platform: macos
            target: toast
          - os: windows-latest
            platform: windows
            target: toast.exe

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: toast
      - uses: actions/checkout@v2
        with:
          repository: toastdotdev/www.toast.dev
          path: www.toast.dev
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          check-latest: true
      - name: Run cargo build
        working-directory: toast
        run: cargo build
      - name: replace toast dep with local toast-node-wrapper
        working-directory: www.toast.dev
        run: |
          sed -i "s/^\s*\"toast\":.*$/  \"toast\": \"../toast/toast-node-wrapper\",/" package.json
      - name: npm install in toast.dev
        working-directory: www.toast.dev
        run: npm ci
        env:
          TOAST_PREVENT_INSTALL: true
      - name: toast incremental
        working-directory: www.toast.dev
        run: npm run build
        env:
          TOAST_BINARY: ../toast/target/debug/toast
      - name: display files
        working-directory: www.toast.dev/public
        run: ls -R
        shell: bash
      - name: deploy
        working-directory: www.toast.dev
        if: github.event.ref == 'refs/heads/main'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WWW_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --dir=public --message ${{ github.event.head_commit.url }}
